name: Deploy to Staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend to Staging
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: FLYCTL_API_TOKEN="$FLY_API_TOKEN" flyctl deploy --remote-only --config fly.staging.toml

      - name: Deploy Frontend to Staging
        working-directory: ./frontend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: FLYCTL_API_TOKEN="$FLY_API_TOKEN" flyctl deploy --remote-only --config fly.staging.toml
